import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { WORKSHEETS } from '@/components/worksheets/data/worksheets';
import { ARTICLES } from '@/components/guides/data/articles';

/**
 * The sitemap is generated by scripts/build-sitemap.mjs, which reads slugs out
 * of the data files with a regex because it runs in plain node. These tests
 * import the real modules and assert the two agree, so that shortcut can never
 * quietly go wrong — and so the sitemap cannot drift behind the content again,
 * which is exactly what had happened (8 URLs listed, 49 pages live).
 */

const publicDir = join(process.cwd(), 'public');
const sitemap = readFileSync(join(publicDir, 'sitemap.xml'), 'utf8');
const rss = readFileSync(join(publicDir, 'guides.xml'), 'utf8');
const robots = readFileSync(join(publicDir, 'robots.txt'), 'utf8');

const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
const paths = locs.map((loc) => new URL(loc).pathname);

describe('sitemap.xml', () => {
  it('is well-formed and non-trivial', () => {
    expect(sitemap.startsWith('<?xml')).toBe(true);
    expect(sitemap).toContain('http://www.sitemaps.org/schemas/sitemap/0.9');
    expect(locs.length).toBeGreaterThan(40);
  });

  it('lists every worksheet', () => {
    const missing = WORKSHEETS.filter(
      (sheet) => !paths.includes(`/Worksheets/${sheet.slug}`),
    ).map((sheet) => sheet.slug);
    expect(missing).toEqual([]);
  });

  it('lists every guide article', () => {
    const missing = ARTICLES.filter(
      (article) => !paths.includes(`/Guides/${article.slug}`),
    ).map((article) => article.slug);
    expect(missing).toEqual([]);
  });

  it('lists every top-level page, including the newer ones', () => {
    for (const path of [
      '/CareerPathfinder',
      '/CollegePlanner',
      '/ParentRoadmap',
      '/Wellness',
      '/Guides',
      '/Worksheets',
      '/About',
      '/Resources',
      '/WorkWithMe',
      '/Privacy',
      '/Terms',
    ]) {
      expect(paths, path).toContain(path);
    }
  });

  it('never lists a URL twice', () => {
    expect(new Set(locs).size).toBe(locs.length);
  });

  it('uses one absolute https origin throughout', () => {
    const origins = new Set(locs.map((loc) => new URL(loc).origin));
    expect(origins.size).toBe(1);
    expect([...origins][0].startsWith('https://')).toBe(true);
  });

  it('does not advertise the API', () => {
    expect(paths.some((path) => path.startsWith('/api'))).toBe(false);
    expect(robots).toContain('Disallow: /api/');
  });
});

describe('guides.xml', () => {
  it('is a valid-looking RSS channel with every article', () => {
    expect(rss.startsWith('<?xml')).toBe(true);
    expect(rss).toContain('<rss version="2.0"');
    for (const article of ARTICLES) {
      expect(rss, article.slug).toContain(`/Guides/${article.slug}`);
    }
  });

  it('escapes text rather than emitting raw ampersands', () => {
    const body = rss.replace(/&(amp|lt|gt|quot|apos|#\d+);/g, '');
    expect(body.includes('&')).toBe(false);
  });

  it('shares the sitemap origin', () => {
    const link = rss.match(/<link>([^<]+)<\/link>/)?.[1] ?? '';
    expect(new URL(link).origin).toBe(new URL(locs[0]).origin);
  });
});
